### ISSUE TITLE
编译不通过，卡在了任务的编译期间

### ISSUE THREAD

**Issue by Hackerofshi** [Knight-ZXW/LancetX#1]
Task :app:transformClassesWithByteXForRdrDebug
AGPBI: {"kind":"warning","text":"API 'MergedFlavor.getApplicationId()' is obsolete and has been replaced with 'Variant.getApplicationId()'.\nIt will be removed in version 7.0 of the Android Gradle plugin.\nGradle Properties must be used to change Variant information.\nFor more information, see https://d.android.com/r/tools/use-properties.\nTo determine what is calling MergedFlavor.getApplicationId(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.","sources":[{}]}
Process init cost time = [13 ms]
Process loading cache cost time = [7 ms]

//gradle 版本
plugins {
    id 'com.android.application' version '7.1.2' apply false
    id 'com.android.library' version '7.1.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.21' apply false
}

二十多分钟了还没有成功

**Comment by Knight-ZXW** [comment]
贴下完整的日志吧，  你是在你们业务的项目工程使用的时候 卡住的吗， 如果有Demo可以复现是最好的

**Comment by Hackerofshi** [comment]
日志就是显示上面那些，执行到这个任务就开始卡住了。

**Comment by Knight-ZXW** [comment]
您的工程 com.android.tools.build:gradle 版本是多少

**Comment by Hackerofshi** [comment]
id 'com.android.application' version '7.1.2' apply false
    id 'com.android.library' version '7.1.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.21' apply false

**Comment by spysoos** [comment]
是不支持 7.0+吗？

**Comment by Knight-ZXW** [comment]
缺少复现场景，无详细日志，线下未复现。 暂时关闭
