### ISSUE TITLE
demo 编译报错   gradle-6.7.1-all

### ISSUE THREAD

**Issue by zhangqilu** [Knight-ZXW/LancetX#10]
Could not GET 'https://jitpack.io/com/bytedance/android/byteX/base-plugin/0.3.0/base-plugin-0.3.0.pom'. Received status code 521 from server:

distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip

**Comment by Knight-ZXW** [comment]
有配置 字节 byteX的仓库地址吗

maven { setUrl("https://artifact.bytedance.com/repository/byteX/") }

**Comment by Knight-ZXW** [comment]
> > 有配置 字节 byteX的仓库地址吗
> > maven { setUrl("https://artifact.bytedance.com/repository/byteX/") }
> > 我直接用的你的demo，我看是有的

现在可以了吗， 好像是 下午 jetpack 服务挂了的原因。 实际上这个资源也不在jetpack上，如果还是出现这个问题的话， 可以把jetpcack 仓库地址删掉 再试下

**Comment by Knight-ZXW** [comment]
没有问题的话，我先close了
