### ISSUE TITLE
koltin data class 会导致fastjson 反序列化失败

### ISSUE THREAD

**Issue by niefanggit** [Knight-ZXW/LancetX#11]
会报没有该实体类没有空构造！

com.alibaba.fastjson.JSONException: default constructor not found. class

**Comment by Knight-ZXW** [comment]
具体 使用场景是什么

**Comment by niefanggit** [comment]
就是简单使用Fastjson，然后开启混淆，就无法反序列化。没有其他特殊的，类要是koltin data class

**Comment by Knight-ZXW** [comment]
> 

我的意思是跟 LancetX 有什么关系，你用LanceX 做了什么操作 出现的异常

**Comment by Knight-ZXW** [comment]
无回复，暂时关闭
