### ISSUE TITLE
gradle输出警告日志

### ISSUE THREAD

**Issue by wsdydeni** [Knight-ZXW/LancetX#18]
能适配一下不 看起来不爽
API 'android.registerTransform' is obsolete.
It will be removed in version 8.0 of the Android Gradle plugin.
The Transform API is removed to improve build performance. Projects that use the
Transform API force the Android Gradle plugin to use a less optimized flow for the
build that can result in large regressions in build times. It’s also difficult to
use the Transform API and combine it with other Gradle features; the replacement
APIs aim to make it easier to extend the build without introducing performance or
correctness issues.

There is no single replacement for the Transform API—there are new, targeted
APIs for each use case. All the replacement APIs are in the
`androidComponents {}` block.

The Transform API uses incremental APIs deprecated since Gradle 7.5. Please add
`android.experimental.legacyTransform.forceNonIncremental=true` to
`gradle.properties` to fix this issue. Note that this will run transforms
non-incrementally and may have a build performance impact.
For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by wsdydeni** [comment]
我的环境 [参考的链接](https://www.cnblogs.com/muouren/p/13949121.html)
```xml
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
```

```groovy
plugins {
    id 'com.android.application' version '7.3.1' apply false
    id 'com.android.library' version '7.3.1' apply false
}
```

我是这么处理的
```groovy
androidComponents {
    onVariants(selector().withBuildType("release")) { ApplicationVariantImpl applicationVariantProperties ->
        StringBuilder sb = new StringBuilder()
        sb.append("productFlavor:$applicationVariantProperties.name, ")
        sb.append("buildType:$applicationVariantProperties.buildType, ")
        sb.append("applicationId:" + applicationVariantProperties.applicationId.get() + ", ")
        println sb

        // API 'MergedFlavor.getApplicationId()' is obsolete and has been replaced with 'VariantProperties.getApplicationId()'.
        // It will be removed in version 5.0 of the Android Gradle plugin.
        if ("debug".equalsIgnoreCase(applicationVariantProperties.buildType)) {
            applicationVariantProperties.applicationId.set(mlwDebugApplicationId)
        }

        //修改打包的名字
        applicationVariantProperties.outputs.each { output ->
            def date = new Date().format('yyyy_MMdd_HHmm')
            def file = output.outputFileName.get()
            def fileName = file.replace(".apk", "_" + android.defaultConfig.versionName + "_" + date + ".apk").replaceFirst("app", "rent_customer").replace("-", "_")
            output.outputFileName.set(fileName)
            println "output.outputFileName:" + output.outputFileName
        }
    }
}
```

**Comment by Knight-ZXW** [comment]
这个API的调用 来自于 byteX,  如果希望在高版本不使用该API ，也得是bytex来兼容
https://github.com/bytedance/ByteX/blob/9ae785ec9e72f9a6cd8de50413000377eeca3512/base-plugin/src/main/java/com/ss/android/ugc/bytex/base/ByteXPlugin.java

**Comment by wsdydeni** [comment]
> 

嗯嗯 我去byteX那里提一下issuse
