### ISSUE TITLE
java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by znbflyingant** [Knight-ZXW/LancetX#19]
![image](https://github.com/Knight-ZXW/LancetX/assets/19476622/8b4d7cdf-e2ca-4bd7-88f1-d872e505d405)
项目编译直接error

**Comment by Knight-ZXW** [comment]
提供下 agp版本

**Comment by DarkAdventurerr** [comment]
> 提供下 agp版本
com.android.tools.build:gradle:7.4.2
搜使用这个版本也会提示报错，和上面的截图一样

**Comment by zouhecan** [comment]
编译报错  agp 7.4.1
![image](https://github.com/Knight-ZXW/LancetX/assets/21106558/09f29e25-39b9-4578-925b-d936f4697729)

**Comment by Knight-ZXW** [comment]
未复现，看调用路径应该是 byteX的兼容问题
