### ISSUE TITLE
io.github.knight-zxw:lancet-runtime:0.01. 依赖拉不下来

### ISSUE THREAD

**Issue by Celinaxin** [Knight-ZXW/LancetX#2]
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find io.github.knight-zxw:lancet-runtime:0.01.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Knight-ZXW** [comment]
可以直接用 0.0.2版本吗 , 注解的API 和Lancex有一些区别，把 原来注解里的 methodName 提取成专门的单独的注解类了
