### ISSUE TITLE
使用之后，会导致assembleDebugAndroidTest 生成的apk 文件，没有classes.dex 文件，test apk 提示invalid

### ISSUE THREAD

**Issue by Celinaxin** [Knight-ZXW/LancetX#4]
使用之后，会导致assembleDebugAndroidTest 生成的apk 文件，没有classes.dex 文件，test apk 提示invalid

**Comment by Knight-ZXW** [comment]
你的 gradle 版本是多少，我测下

**Comment by Celinaxin** [comment]
classpath "com.android.tools.build:gradle:4.1.0"

**Comment by Knight-ZXW** [comment]
方便的话 提供个可复现的Demo，我未能复现
