### ISSUE TITLE
工程clone下来编译不过

### ISSUE THREAD

**Issue by MrsLEO** [Knight-ZXW/LancetX#5]
A problem occurred configuring root project 'LancetX'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.github.knight-zxw:lancet-plugin:0.0.1.9-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/lancet-plugin-0.0.1.9-SNAPSHOT.pom
       - https://dl.google.com/dl/android/maven2/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/lancet-plugin-0.0.1.9-SNAPSHOT.pom
       - https://jitpack.io/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/lancet-plugin-0.0.1.9-SNAPSHOT.pom
       - https://artifact.bytedance.com/repository/byteX/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/maven-metadata.xml
       - https://artifact.bytedance.com/repository/byteX/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/lancet-plugin-0.0.1.9-SNAPSHOT.pom
       - https://jcenter.bintray.com/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/io/github/knight-zxw/lancet-plugin/0.0.1.9-SNAPSHOT/lancet-plugin-0.0.1.9-SNAPSHOT.pom

**Comment by Knight-ZXW** [comment]
改成0.0.3就行， 这个SNAPSHOT是我本地调试的版本，后面我注意下，不要带到远程分支周，

**Comment by MrsLEO** [comment]
> 改成0.0.3就行， 这个SNAPSHOT是我本地调试的版本，后面我注意下，本地调试的版本不要带到远程分支中

是不是@Proxy在lancetX中不起作用啊，发现用了没有达到lancet的同样效果，还望解惑下
