### ISSUE TITLE
hook abstract 抽象方法

### ISSUE THREAD

**Issue by BoringBoy0515** [Knight-ZXW/LancetX#6]
怎么做抽象方法的Proxy那？比如想hook  android.content.pm.PackageManager中的函数

**Comment by Knight-ZXW** [comment]
@Proxy 可以实现，不过如果这个函数调用的地方比较多的话，生成的额外字节码也会比较多。

也可以考虑用 @RepalceInvoke 注解实现， 举个例子，比如想要代理应用内 调用 PackageManager.isInstantApp的函数的话，可以改成下面的写法。 


  @ReplaceInvoke(isStatic = false)
  @TargetClass(value = "android.content.pm.PackageManager",scope = Scope.SELF)
  @TargetMethod(methodName = "isInstantApp")
  public static boolean isInstantApp(PackageManager packageManager){
      if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
          boolean r = packageManager.isInstantApp();
      }
      return true;
  }
