### ISSUE TITLE
可以做类似，AspectJ的Pointcut功能吗？

### ISSUE THREAD

**Issue by BoringBoy0515** [Knight-ZXW/LancetX#8]
hello，麻烦问下哈，我有看到demo里有一个AppSpeed的测试功能。
想问下LancetX 可以支持 自定义一个方法注解，可以针对添加该注解的方法进行Insert吗？

**Comment by Knight-ZXW** [comment]
暂未支持。 如果支持这样的功能，最终实现的效果会和 Aspect差不多， 因为标记了注解的函数的参数应该不是固定的，所有 编写 Hook函数的时候，需要用一个包装类 来收集调用原函数的参数对象。
